〇予想と回答


  予想
  図解はmdファイルに記載
  
・f3
  // NOTE: f2の動作
  //
  // 回答:
  // 0秒後に A が出力され、その後にエラー処理が実行され、Bが出力される。その後にCが出力される。
  //
  // 説明:
  // wait0の解決後に logA が実行され、wait2().then(errX) の解決後 (B 出力),その後 finallyが実行されlogCが実行されるため。

  回答
PS C:\Users\sumi6\javascript\github\sample\exercises\ch13\ex02> node index.js
C
A
file:///C:/Users/sumi6/javascript/github/sample/exercises/ch13/ex02/index.js:34
  throw new Error("X");
        ^

Error: X
    at errX (file:///C:/Users/sumi6/javascript/github/sample/exercises/ch13/ex02/index.js:34:9)

Node.js v22.14.0
最初にCが出力され、ほぼ同時にAが出力された。Bは出力されずエラーメッセージが表示された。

・f4
  // NOTE: f4の動作
  //
  // 回答:
  // 2秒後に A が出力され、return 40で40を返す。その後に1秒後に、Bが出力され、return100で100を返す。その後に変数vの値が表示される。
  //
  // 説明:
  // wait2の解決後に logA が実行され、wait(1000)の解決後 (B 出力),その後vの値100が出力される。

回答
  PS C:\Users\sumi6\javascript\github\sample\exercises\ch13\ex02> node index.js
A
B
100

予想通りの結果に見える。

・f5
  // NOTE: f4の動作
  //
  // 回答:
  // 2秒後に A が出力され、return 40で40を返す。その後に1秒後に、Bが出力され、return100で100を返す。その後に変数vの値が表示される。
  //
  // 説明:
  // wait2の解決後に logA が実行され、wait(1000)の解決後 (B 出力),その後vの値100が出力される。

回答
  PS C:\Users\sumi6\javascript\github\sample\exercises\ch13\ex02> node index.js
A
B
100
